[theme]
primaryColor="#000000"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F7F9FB"
textColor="#333333"
font="sans serif"

[server]
maxUploadSize=200
enableXsrfProtection=true

[browser]
gatherUsageStats=false